from django.utils.translation import gettext_lazy as _

COUNTRY_CHOICES = (
    ('004',_('Afghanistan')),
    ('248',_('Åland Islands')),
    ('008',_('Albania')),
    ('012',_('Algeria')),
    ('016',_('American Samoa')),
    ('020',_('Andorra')),
    ('024',_('Angola')),
    ('660',_('Anguilla')),
    ('028',_('Antigua and Barbuda')),
    ('032',_('Argentina')),
    ('051',_('Armenia')),
    ('533',_('Aruba')),
    ('036',_('Australia')),
    ('040',_('Austria')),
    ('031',_('Azerbaijan')),
    ('044',_('Bahamas')),
    ('048',_('Bahrain')),
    ('050',_('Bangladesh')),
    ('052',_('Barbados')),
    ('112',_('Belarus')),
    ('056',_('Belgium')),
    ('084',_('Belize')),
    ('204',_('Benin')),
    ('060',_('Bermuda')),
    ('064',_('Bhutan')),
    ('068',_('Bolivia (Plurinational State of)')),
    ('535',_('Bonaire, Saint Eustatius and Saba')),
    ('070',_('Bosnia and Herzegovina')),
    ('072',_('Botswana')),
    ('076',_('Brazil')),
    ('092',_('British Virgin Islands')),
    ('096',_('Brunei Darussalam')),
    ('100',_('Bulgaria')),
    ('854',_('Burkina Faso')),
    ('108',_('Burundi')),
    ('116',_('Cambodia')),
    ('120',_('Cameroon')),
    ('124',_('Canada')),
    ('132',_('Cape Verde')),
    ('136',_('Cayman Islands')),
    ('140',_('Central African Republic')),
    ('148',_('Chad')),
    ('830',_('Channel Islands')),
    ('152',_('Chile')),
    ('156',_('China')),
    ('344',_('China, Hong Kong Special Administrative Region')),
    ('446',_('China, Macao Special Administrative Region')),
    ('170',_('Colombia')),
    ('174',_('Comoros')),
    ('178',_('Congo')),
    ('184',_('Cook Islands')),
    ('188',_('Costa Rica')),
    ('384',_('Côte dIvoire')),
    ('191',_('Croatia')),
    ('192',_('Cuba')),
    ('531',_('Curaçao')),
    ('196',_('Cyprus')),
    ('203',_('Czech Republic')),
    ('408',_('Democratic Peoples Republic of Korea')),
    ('180',_('Democratic Republic of the Congo')),
    ('208',_('Denmark')),
    ('262',_('Djibouti')),
    ('212',_('Dominica')),
    ('214',_('Dominican Republic')),
    ('218',_('Ecuador')),
    ('818',_('Egypt')),
    ('222',_('El Salvador')),
    ('226',_('Equatorial Guinea')),
    ('232',_('Eritrea')),
    ('233',_('Estonia')),
    ('231',_('Ethiopia')),
    ('234',_('Faeroe Islands')),
    ('238',_('Falkland Islands (Malvinas)')),
    ('242',_('Fiji')),
    ('246',_('Finland')),
    ('250',_('France')),
    ('254',_('French Guiana')),
    ('258',_('French Polynesia')),
    ('266',_('Gabon')),
    ('270',_('Gambia')),
    ('268',_('Georgia')),
    ('276',_('Germany')),
    ('288',_('Ghana')),
    ('292',_('Gibraltar')),
    ('300',_('Greece')),
    ('304',_('Greenland')),
    ('308',_('Grenada')),
    ('312',_('Guadeloupe')),
    ('316',_('Guam')),
    ('320',_('Guatemala')),
    ('831',_('Guernsey')),
    ('324',_('Guinea')),
    ('624',_('Guinea-Bissau')),
    ('328',_('Guyana')),
    ('332',_('Haiti')),
    ('336',_('Holy See')),
    ('340',_('Honduras')),
    ('348',_('Hungary')),
    ('352',_('Iceland')),
    ('356',_('India')),
    ('360',_('Indonesia')),
    ('364',_('Iran (Islamic Republic of)')),
    ('368',_('Iraq')),
    ('372',_('Ireland')),
    ('833',_('Isle of Man')),
    ('376',_('Israel')),
    ('380',_('Italy')),
    ('388',_('Jamaica')),
    ('392',_('Japan')),
    ('832',_('Jersey')),
    ('400',_('Jordan')),
    ('398',_('Kazakhstan')),
    ('404',_('Kenya')),
    ('296',_('Kiribati')),
    ('414',_('Kuwait')),
    ('417',_('Kyrgyzstan')),
    ('418',_('Lao Peoples Democratic Republic')),
    ('428',_('Latvia')),
    ('422',_('Lebanon')),
    ('426',_('Lesotho')),
    ('430',_('Liberia')),
    ('434',_('Libyan Arab Jamahiriya')),
    ('438',_('Liechtenstein')),
    ('440',_('Lithuania')),
    ('442',_('Luxembourg')),
    ('450',_('Madagascar')),
    ('454',_('Malawi')),
    ('458',_('Malaysia')),
    ('462',_('Maldives')),
    ('466',_('Mali')),
    ('470',_('Malta')),
    ('584',_('Marshall Islands')),
    ('474',_('Martinique')),
    ('478',_('Mauritania')),
    ('480',_('Mauritius')),
    ('175',_('Mayotte')),
    ('484',_('Mexico')),
    ('583',_('Micronesia (Federated States of)')),
    ('492',_('Monaco')),
    ('496',_('Mongolia')),
    ('499',_('Montenegro')),
    ('500',_('Montserrat')),
    ('504',_('Morocco')),
    ('508',_('Mozambique')),
    ('104',_('Myanmar')),
    ('516',_('Namibia')),
    ('520',_('Nauru')),
    ('524',_('Nepal')),
    ('528',_('Netherlands')),
    ('540',_('New Caledonia')),
    ('554',_('New Zealand')),
    ('558',_('Nicaragua')),
    ('562',_('Niger')),
    ('566',_('Nigeria')),
    ('570',_('Niue')),
    ('574',_('Norfolk Island')),
    ('580',_('Northern Mariana Islands')),
    ('578',_('Norway')),
    ('275',_('Occupied Palestinian Territory')),
    ('512',_('Oman')),
    ('586',_('Pakistan')),
    ('585',_('Palau')),
    ('591',_('Panama')),
    ('598',_('Papua New Guinea')),
    ('600',_('Paraguay')),
    ('604',_('Peru')),
    ('608',_('Philippines')),
    ('612',_('Pitcairn')),
    ('616',_('Poland')),
    ('620',_('Portugal')),
    ('630',_('Puerto Rico')),
    ('634',_('Qatar')),
    ('410',_('Republic of Korea')),
    ('498',_('Republic of Moldova')),
    ('638',_('Réunion')),
    ('642',_('Romania')),
    ('643',_('Russian Federation')),
    ('646',_('Rwanda')),
    ('652',_('Saint-Barthélemy')),
    ('654',_('Saint Helena')),
    ('659',_('Saint Kitts and Nevis')),
    ('662',_('Saint Lucia')),
    ('663',_('Saint-Martin (French part)')),
    ('666',_('Saint Pierre and Miquelon')),
    ('670',_('Saint Vincent and the Grenadines')),
    ('882',_('Samoa')),
    ('674',_('San Marino')),
    ('678',_('Sao Tome and Principe')),
    ('680',_('Sark')),
    ('682',_('Saudi Arabia')),
    ('686',_('Senegal')),
    ('688',_('Serbia')),
    ('690',_('Seychelles')),
    ('694',_('Sierra Leone')),
    ('702',_('Singapore')),
    ('534',_('Sint Maarten (Dutch part)')),
    ('703',_('Slovakia')),
    ('705',_('Slovenia')),
    ('090',_('Solomon Islands')),
    ('706',_('Somalia')),
    ('710',_('South Africa')),
    ('728',_('South Sudan')),
    ('724',_('Spain')),
    ('144',_('Sri Lanka')),
    ('729',_('Sudan')),
    ('740',_('Suriname')),
    ('744',_('Svalbard and Jan Mayen Islands')),
    ('748',_('Swaziland')),
    ('752',_('Sweden')),
    ('756',_('Switzerland')),
    ('760',_('Syrian Arab Republic')),
    ('762',_('Tajikistan')),
    ('764',_('Thailand')),
    ('807',_('The former Yugoslav Republic of Macedonia')),
    ('626',_('Timor-Leste')),
    ('768',_('Togo')),
    ('772',_('Tokelau')),
    ('776',_('Tonga')),
    ('780',_('Trinidad and Tobago')),
    ('788',_('Tunisia')),
    ('792',_('Turkey')),
    ('795',_('Turkmenistan')),
    ('796',_('Turks and Caicos Islands')),
    ('798',_('Tuvalu')),
    ('800',_('Uganda')),
    ('804',_('Ukraine')),
    ('784',_('United Arab Emirates')),
    ('826',_('United Kingdom of Great Britain and Northern Ireland')),
    ('834',_('United Republic of Tanzania')),
    ('840',_('United States of America')),
    ('850',_('United States Virgin Islands')),
    ('858',_('Uruguay')),
    ('860',_('Uzbekistan')),
    ('548',_('Vanuatu')),
    ('862',_('Venezuela (Bolivarian Republic of)')),
    ('704',_('Viet Nam')),
    ('876',_('Wallis and Futuna Islands')),
    ('732',_('Western Sahara')),
    ('887',_('Yemen')),
    ('894',_('Zambia')),
    ('716',_('Zimbabwe')),
)