INSERT INTO `waybill_dispatchpoint` (`ORIGIN_LOC_NAME`,`ORIGIN_LOCATION_CODE`,`ORIGIN_WH_NAME`,`ORIGIN_WH_CODE`)
VALUES
    ('RAMALLAH', 'R2NX', 'RAMALLAH_SUP_WH', 'R2NX007'),
    ('QALANDIA', 'QD9X', 'QALANDIA_WFP_', 'QD9X002'),
    ('ASHQELON', 'QX7X', 'ASHQELON_WFP', 'QX7X001'),
    ('ASHDOD', 'ASHX', 'ASHDOD_OVERSEAS_BONDED', 'ASHX004'),
    ('JERICHO', 'J5UX', 'JERICHO_SUP_WH', 'J5UX007'),
    ('CAIRO', 'CROX', 'CAIRO SUPPLIER WH', 'CROX006'),
    ('GAZA TOWN', 'GZTX', 'DELTA_WH', 'GZTX029'),
    ('NABLUS', 'N5BX', 'NABLUS_SUP_WH', 'N5BX006'),
    ('GAZA TOWN', 'GZTX', 'GAZA_WH 1', 'GZTX008'),
    ('EAST JERUSALEM', 'JERX', 'ATAROT_SUP_WH', 'JERX012'),
    ('ASHDOD', 'ASHX', 'ASHDOD PORT SILO', 'ASHX008'),
    ('LIRA', 'LRAX', 'LIRA_EDP_WH', 'LRAX002'),
    ('DAIR ALBALLAH', 'D2TX', 'DAIR ALBALLAH_SUP_WH', 'D2TX008'),
    ('BETHANY', 'B8AX', 'BETHANY_SUP_WH', 'B8AX005');
