# encoding: utf-8
import datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models

class Migration(SchemaMigration):

    def forwards(self, orm):
        
        # Deleting field 'LtiWithStock.id'
        db.delete_column('ets_ltiwithstock', 'id')

        # Adding field 'LtiWithStock.slug'
        db.add_column('ets_ltiwithstock', 'slug', self.gf('autoslug.fields.AutoSlugField')(unique_with=(), max_length=50, primary_key=True, default=1, unique=True, populate_from=None, db_index=True), keep_default=False)


    def backwards(self, orm):
        
        # User chose to not deal with backwards NULL issues for 'LtiWithStock.id'
        raise RuntimeError("Cannot reverse this migration. 'LtiWithStock.id' and its values cannot be restored.")

        # Deleting field 'LtiWithStock.slug'
        db.delete_column('ets_ltiwithstock', 'slug')


    models = {
        'auth.group': {
            'Meta': {'object_name': 'Group'},
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '80'}),
            'permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'})
        },
        'auth.permission': {
            'Meta': {'ordering': "('content_type__app_label', 'content_type__model', 'codename')", 'unique_together': "(('content_type', 'codename'),)", 'object_name': 'Permission'},
            'codename': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['contenttypes.ContentType']"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'})
        },
        'auth.user': {
            'Meta': {'object_name': 'User'},
            'date_joined': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'email': ('django.db.models.fields.EmailField', [], {'max_length': '75', 'blank': 'True'}),
            'first_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'groups': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['auth.Group']", 'symmetrical': 'False', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_staff': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_superuser': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'last_login': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'last_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'password': ('django.db.models.fields.CharField', [], {'max_length': '128'}),
            'user_permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'}),
            'username': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '30'})
        },
        'contenttypes.contenttype': {
            'Meta': {'ordering': "('name',)", 'unique_together': "(('app_label', 'model'),)", 'object_name': 'ContentType', 'db_table': "'django_content_type'"},
            'app_label': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'model': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'})
        },
        'ets.compaslogger': {
            'Meta': {'object_name': 'CompasLogger', 'db_table': "u'loggercompas'"},
            'action': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'data_in': ('django.db.models.fields.CharField', [], {'max_length': '5000', 'blank': 'True'}),
            'data_out': ('django.db.models.fields.CharField', [], {'max_length': '5000', 'blank': 'True'}),
            'errorDisp': ('django.db.models.fields.CharField', [], {'max_length': '2000', 'blank': 'True'}),
            'errorRec': ('django.db.models.fields.CharField', [], {'max_length': '2000', 'blank': 'True'}),
            'lti': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'timestamp': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['auth.User']"}),
            'wb': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['ets.Waybill']", 'primary_key': 'True'})
        },
        'ets.dispatchdetail': {
            'Meta': {'object_name': 'DispatchDetail', 'db_table': "u'dispatch_details'"},
            'allocation_destination_code': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'code': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['ets.DispatchMaster']"}),
            'comm_category_code': ('django.db.models.fields.CharField', [], {'max_length': '9'}),
            'commodity_code': ('django.db.models.fields.CharField', [], {'max_length': '18'}),
            'document_code': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'last_mod_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'last_mod_user': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'londtl_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'lonmst_id': ('django.db.models.fields.CharField', [], {'max_length': '25', 'blank': 'True'}),
            'number_of_units': ('django.db.models.fields.IntegerField', [], {}),
            'offid': ('django.db.models.fields.CharField', [], {'max_length': '13', 'blank': 'True'}),
            'origin_id': ('django.db.models.fields.CharField', [], {'max_length': '23', 'blank': 'True'}),
            'package_code': ('django.db.models.fields.CharField', [], {'max_length': '17'}),
            'quality': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            'quantity_gross': ('django.db.models.fields.DecimalField', [], {'max_digits': '11', 'decimal_places': '3'}),
            'quantity_net': ('django.db.models.fields.DecimalField', [], {'max_digits': '11', 'decimal_places': '3'}),
            'recv_pack': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'rpydtl_id': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'send_pack': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'si_record_id': ('django.db.models.fields.CharField', [], {'max_length': '25', 'null': 'True', 'blank': 'True'}),
            'unit_weight_gross': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '8', 'decimal_places': '3', 'blank': 'True'}),
            'unit_weight_net': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '8', 'decimal_places': '3', 'blank': 'True'})
        },
        'ets.dispatchmaster': {
            'Meta': {'object_name': 'DispatchMaster', 'db_table': "u'dispatch_masters'"},
            'activity_ouc': ('django.db.models.fields.CharField', [], {'max_length': '13', 'blank': 'True'}),
            'atl_li_code': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'certifing_title': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'code': ('django.db.models.fields.CharField', [], {'max_length': '25', 'primary_key': 'True'}),
            'comments': ('django.db.models.fields.CharField', [], {'max_length': '250', 'blank': 'True'}),
            'container_number': ('django.db.models.fields.CharField', [], {'max_length': '15', 'blank': 'True'}),
            'customised': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'destination_code': ('django.db.models.fields.CharField', [], {'max_length': '13', 'blank': 'True'}),
            'destination_location_code': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'dispatch_date': ('django.db.models.fields.DateField', [], {}),
            'document_code': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'driver_name': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'intdlv_code': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'intvyg_code': ('django.db.models.fields.CharField', [], {'max_length': '25', 'blank': 'True'}),
            'last_mod_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'last_mod_user': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'license': ('django.db.models.fields.CharField', [], {'max_length': '20', 'blank': 'True'}),
            'lndarrm_code': ('django.db.models.fields.CharField', [], {'max_length': '25', 'blank': 'True'}),
            'loading_date': ('django.db.models.fields.DateField', [], {}),
            'loan_id': ('django.db.models.fields.CharField', [], {'max_length': '25', 'blank': 'True'}),
            'lti_id': ('django.db.models.fields.CharField', [], {'max_length': '25', 'blank': 'True'}),
            'modetrans_code': ('django.db.models.fields.CharField', [], {'max_length': '2'}),
            'nmbplt_id': ('django.db.models.fields.CharField', [], {'max_length': '25', 'blank': 'True'}),
            'nmbtrl_id': ('django.db.models.fields.CharField', [], {'max_length': '25', 'blank': 'True'}),
            'notify_indicator': ('django.db.models.fields.CharField', [], {'max_length': '1', 'blank': 'True'}),
            'notify_org_unit_code': ('django.db.models.fields.CharField', [], {'max_length': '13', 'blank': 'True'}),
            'offid': ('django.db.models.fields.CharField', [], {'max_length': '13', 'blank': 'True'}),
            'org_unit_code': ('django.db.models.fields.CharField', [], {'max_length': '13'}),
            'organization_id': ('django.db.models.fields.CharField', [], {'max_length': '12'}),
            'origin_code': ('django.db.models.fields.CharField', [], {'max_length': '13', 'blank': 'True'}),
            'origin_descr': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'origin_location_code': ('django.db.models.fields.CharField', [], {'max_length': '13'}),
            'origin_type': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            'person_code': ('django.db.models.fields.CharField', [], {'max_length': '7'}),
            'person_ouc': ('django.db.models.fields.CharField', [], {'max_length': '13'}),
            'printed_indicator': ('django.db.models.fields.CharField', [], {'max_length': '1', 'blank': 'True'}),
            'pro_activity_code': ('django.db.models.fields.CharField', [], {'max_length': '6', 'blank': 'True'}),
            'recv_pack': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'send_pack': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'supplier1_ouc': ('django.db.models.fields.CharField', [], {'max_length': '13'}),
            'supplier2_ouc': ('django.db.models.fields.CharField', [], {'max_length': '13', 'blank': 'True'}),
            'trailer_plate': ('django.db.models.fields.CharField', [], {'max_length': '20', 'blank': 'True'}),
            'tran_type_code': ('django.db.models.fields.CharField', [], {'max_length': '4'}),
            'tran_type_descr': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'trans_contractor_code': ('django.db.models.fields.CharField', [], {'max_length': '4'}),
            'trans_subcontractor_code': ('django.db.models.fields.CharField', [], {'max_length': '4', 'blank': 'True'}),
            'vehicle_registration': ('django.db.models.fields.CharField', [], {'max_length': '20', 'blank': 'True'})
        },
        'ets.dispatchpoint': {
            'ACTIVE_START_DATE': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'Meta': {'object_name': 'DispatchPoint'},
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'origin_loc_name': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'origin_location_code': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'origin_wh_code': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'origin_wh_name': ('django.db.models.fields.CharField', [], {'max_length': '80', 'blank': 'True'})
        },
        'ets.epiclossdamages': {
            'Meta': {'object_name': 'EpicLossDamages', 'db_table': "u'epic_lossdamagereason'"},
            'cause': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'comm_category_code': ('django.db.models.fields.CharField', [], {'max_length': '9'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'type': ('django.db.models.fields.CharField', [], {'max_length': '1'})
        },
        'ets.epicperson': {
            'Meta': {'object_name': 'EpicPerson', 'db_table': "u'epic_persons'"},
            'code': ('django.db.models.fields.CharField', [], {'max_length': '7'}),
            'document_number': ('django.db.models.fields.CharField', [], {'max_length': '25', 'blank': 'True'}),
            'e_mail_address': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'effective_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'expiry_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'fax_number': ('django.db.models.fields.CharField', [], {'max_length': '20', 'blank': 'True'}),
            'first_name': ('django.db.models.fields.CharField', [], {'max_length': '25'}),
            'last_name': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'location_code': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'mobile_phone_number': ('django.db.models.fields.CharField', [], {'max_length': '20', 'blank': 'True'}),
            'official_tel_number': ('django.db.models.fields.CharField', [], {'max_length': '20', 'blank': 'True'}),
            'org_unit_code': ('django.db.models.fields.CharField', [], {'max_length': '13'}),
            'organization_id': ('django.db.models.fields.CharField', [], {'max_length': '12'}),
            'person_pk': ('django.db.models.fields.CharField', [], {'max_length': '20', 'primary_key': 'True'}),
            'title': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'type_of_document': ('django.db.models.fields.CharField', [], {'max_length': '2', 'blank': 'True'})
        },
        'ets.epicstock': {
            'Meta': {'object_name': 'EpicStock', 'db_table': "u'epic_stock'"},
            'allocation_code': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'cmmname': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'comm_category_code': ('django.db.models.fields.CharField', [], {'max_length': '9'}),
            'commodity_code': ('django.db.models.fields.CharField', [], {'max_length': '18'}),
            'number_of_units': ('django.db.models.fields.IntegerField', [], {}),
            'origin_id': ('django.db.models.fields.CharField', [], {'max_length': '23'}),
            'package_code': ('django.db.models.fields.CharField', [], {'max_length': '17'}),
            'packagename': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'project_wbs_element': ('django.db.models.fields.CharField', [], {'max_length': '24', 'blank': 'True'}),
            'qualitycode': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            'qualitydescr': ('django.db.models.fields.CharField', [], {'max_length': '11', 'blank': 'True'}),
            'quantity_gross': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '12', 'decimal_places': '3', 'blank': 'True'}),
            'quantity_net': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '12', 'decimal_places': '3', 'blank': 'True'}),
            'reference_number': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'si_code': ('django.db.models.fields.CharField', [], {'max_length': '8'}),
            'si_record_id': ('django.db.models.fields.CharField', [], {'max_length': '25'}),
            'wh_code': ('django.db.models.fields.CharField', [], {'max_length': '13'}),
            'wh_country': ('django.db.models.fields.CharField', [], {'max_length': '15'}),
            'wh_location': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'wh_name': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'wh_pk': ('django.db.models.fields.CharField', [], {'max_length': '90', 'primary_key': 'True'}),
            'wh_regional': ('django.db.models.fields.CharField', [], {'max_length': '4', 'blank': 'True'})
        },
        'ets.loadingdetail': {
            'Meta': {'object_name': 'LoadingDetail'},
            'loadingDetailSentToCompas': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'numberUnitsDamaged': ('django.db.models.fields.DecimalField', [], {'default': '0', 'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'numberUnitsGood': ('django.db.models.fields.DecimalField', [], {'default': '0', 'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'numberUnitsLoaded': ('django.db.models.fields.DecimalField', [], {'default': '0', 'max_digits': '10', 'decimal_places': '3'}),
            'numberUnitsLost': ('django.db.models.fields.DecimalField', [], {'default': '0', 'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'order_item': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'loading_details'", 'to': "orm['ets.LtiWithStock']"}),
            'overOffloadUnits': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'overloadedUnits': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'slug': ('autoslug.fields.AutoSlugField', [], {'unique_with': '()', 'max_length': '50', 'primary_key': 'True', 'unique': 'True', 'populate_from': 'None', 'db_index': 'True'}),
            'unitsDamagedReason': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'LD_DamagedReason'", 'null': 'True', 'to': "orm['ets.EpicLossDamages']"}),
            'unitsDamagedType': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'LD_DamagedType'", 'null': 'True', 'to': "orm['ets.EpicLossDamages']"}),
            'unitsLostReason': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'LD_LostReason'", 'null': 'True', 'to': "orm['ets.EpicLossDamages']"}),
            'unitsLostType': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'LD_LossType'", 'null': 'True', 'to': "orm['ets.EpicLossDamages']"}),
            'wbNumber': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'loading_details'", 'to': "orm['ets.Waybill']"})
        },
        'ets.loadingdetailauditlogentry': {
            'Meta': {'ordering': "('-action_date',)", 'object_name': 'LoadingDetailAuditLogEntry'},
            'action_date': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'action_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'action_type': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            'action_user': ('audit_log.models.fields.LastUserField', [], {'related_name': "'_loadingdetail_audit_log_entry'", 'null': 'True', 'to': "orm['auth.User']"}),
            'loadingDetailSentToCompas': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'numberUnitsDamaged': ('django.db.models.fields.DecimalField', [], {'default': '0', 'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'numberUnitsGood': ('django.db.models.fields.DecimalField', [], {'default': '0', 'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'numberUnitsLoaded': ('django.db.models.fields.DecimalField', [], {'default': '0', 'max_digits': '10', 'decimal_places': '3'}),
            'numberUnitsLost': ('django.db.models.fields.DecimalField', [], {'default': '0', 'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'order_item': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'_auditlog_loading_details'", 'to': "orm['ets.LtiWithStock']"}),
            'overOffloadUnits': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'overloadedUnits': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'slug': ('autoslug.fields.AutoSlugField', [], {'unique_with': '()', 'max_length': '50', 'populate_from': 'None', 'db_index': 'True'}),
            'unitsDamagedReason': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'_auditlog_LD_DamagedReason'", 'null': 'True', 'to': "orm['ets.EpicLossDamages']"}),
            'unitsDamagedType': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'_auditlog_LD_DamagedType'", 'null': 'True', 'to': "orm['ets.EpicLossDamages']"}),
            'unitsLostReason': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'_auditlog_LD_LostReason'", 'null': 'True', 'to': "orm['ets.EpicLossDamages']"}),
            'unitsLostType': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'_auditlog_LD_LossType'", 'null': 'True', 'to': "orm['ets.EpicLossDamages']"}),
            'wbNumber': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'_auditlog_loading_details'", 'to': "orm['ets.Waybill']"})
        },
        'ets.ltioriginal': {
            'Meta': {'object_name': 'LtiOriginal', 'db_table': "u'epic_lti'"},
            'cmmname': ('django.db.models.fields.CharField', [], {'max_length': '100', 'db_column': "'CMMNAME'", 'blank': 'True'}),
            'code': ('django.db.models.fields.CharField', [], {'max_length': '40', 'db_column': "'CODE'"}),
            'comm_category_code': ('django.db.models.fields.CharField', [], {'max_length': '9', 'db_column': "'COMM_CATEGORY_CODE'"}),
            'commodity_code': ('django.db.models.fields.CharField', [], {'max_length': '18', 'db_column': "'COMMODITY_CODE'"}),
            'consegnee_code': ('django.db.models.fields.CharField', [], {'max_length': '12', 'db_column': "'CONSEGNEE_CODE'"}),
            'consegnee_name': ('django.db.models.fields.CharField', [], {'max_length': '80', 'db_column': "'CONSEGNEE_NAME'"}),
            'destination_loc_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'db_column': "'DESTINATION_LOC_NAME'"}),
            'destination_location_code': ('django.db.models.fields.CharField', [], {'max_length': '10', 'db_column': "'DESTINATION_LOCATION_CODE'"}),
            'expiry_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'db_column': "'EXPIRY_DATE'", 'blank': 'True'}),
            'lti_date': ('django.db.models.fields.DateField', [], {'db_column': "'LTI_DATE'"}),
            'lti_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'db_column': "'LTI_ID'"}),
            'lti_pk': ('django.db.models.fields.CharField', [], {'max_length': '50', 'primary_key': 'True', 'db_column': "'LTI_PK'"}),
            'number_of_units': ('django.db.models.fields.DecimalField', [], {'db_column': "'NUMBER_OF_UNITS'", 'decimal_places': '0', 'max_digits': '7'}),
            'origin_loc_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'db_column': "'ORIGIN_LOC_NAME'"}),
            'origin_location_code': ('django.db.models.fields.CharField', [], {'max_length': '10', 'db_column': "'ORIGIN_LOCATION_CODE'"}),
            'origin_type': ('django.db.models.fields.CharField', [], {'max_length': '1', 'db_column': "'ORIGIN_TYPE'"}),
            'origin_wh_code': ('django.db.models.fields.CharField', [], {'max_length': '13', 'db_column': "'ORIGIN_WH_CODE'", 'blank': 'True'}),
            'origin_wh_name': ('django.db.models.fields.CharField', [], {'max_length': '50', 'db_column': "'ORIGIN_WH_NAME'", 'blank': 'True'}),
            'origintype_desc': ('django.db.models.fields.CharField', [], {'max_length': '12', 'db_column': "'ORIGINTYPE_DESC'", 'blank': 'True'}),
            'project_wbs_element': ('django.db.models.fields.CharField', [], {'max_length': '24', 'db_column': "'PROJECT_WBS_ELEMENT'", 'blank': 'True'}),
            'quantity_gross': ('django.db.models.fields.DecimalField', [], {'db_column': "'QUANTITY_GROSS'", 'decimal_places': '3', 'max_digits': '11'}),
            'quantity_net': ('django.db.models.fields.DecimalField', [], {'db_column': "'QUANTITY_NET'", 'decimal_places': '3', 'max_digits': '11'}),
            'requested_dispatch_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'db_column': "'REQUESTED_DISPATCH_DATE'", 'blank': 'True'}),
            'si_code': ('django.db.models.fields.CharField', [], {'max_length': '8', 'db_column': "'SI_CODE'"}),
            'si_record_id': ('django.db.models.fields.CharField', [], {'max_length': '25', 'db_column': "'SI_RECORD_ID'", 'blank': 'True'}),
            'transport_code': ('django.db.models.fields.CharField', [], {'max_length': '4', 'db_column': "'TRANSPORT_CODE'"}),
            'transport_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'db_column': "'TRANSPORT_NAME'"}),
            'transport_ouc': ('django.db.models.fields.CharField', [], {'max_length': '13', 'db_column': "'TRANSPORT_OUC'"}),
            'unit_weight_gross': ('django.db.models.fields.DecimalField', [], {'blank': 'True', 'null': 'True', 'db_column': "'UNIT_WEIGHT_GROSS'", 'decimal_places': '3', 'max_digits': '8'}),
            'unit_weight_net': ('django.db.models.fields.DecimalField', [], {'blank': 'True', 'null': 'True', 'db_column': "'UNIT_WEIGHT_NET'", 'decimal_places': '3', 'max_digits': '8'})
        },
        'ets.ltiwithstock': {
            'Meta': {'object_name': 'LtiWithStock'},
            'lti_code': ('django.db.models.fields.CharField', [], {'max_length': '20', 'db_index': 'True'}),
            'lti_line': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'ltistockrel'", 'to': "orm['ets.LtiOriginal']"}),
            'slug': ('autoslug.fields.AutoSlugField', [], {'unique_with': '()', 'max_length': '50', 'primary_key': 'True', 'unique': 'True', 'populate_from': 'None', 'db_index': 'True'}),
            'stock_item': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'ltistockrel'", 'to': "orm['ets.EpicStock']"})
        },
        'ets.packagingdescriptionshort': {
            'Meta': {'object_name': 'PackagingDescriptionShort'},
            'packageCode': ('django.db.models.fields.CharField', [], {'max_length': '5', 'primary_key': 'True'}),
            'packageShortName': ('django.db.models.fields.CharField', [], {'max_length': '10'})
        },
        'ets.place': {
            'Meta': {'ordering': "('name',)", 'object_name': 'Place', 'db_table': "u'epic_geo'"},
            'country_code': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'geo_name': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'geo_point_code': ('django.db.models.fields.CharField', [], {'max_length': '4'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'org_code': ('django.db.models.fields.CharField', [], {'max_length': '7', 'primary_key': 'True'}),
            'organization_id': ('django.db.models.fields.CharField', [], {'max_length': '20', 'blank': 'True'}),
            'reporting_code': ('django.db.models.fields.CharField', [], {'max_length': '7'})
        },
        'ets.receptionpoint': {
            'ACTIVE_START_DATE': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'LOCATION_CODE': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'LOC_NAME': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'Meta': {'ordering': "('LOC_NAME', 'consegnee_name')", 'object_name': 'ReceptionPoint'},
            'consegnee_code': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'consegnee_name': ('django.db.models.fields.CharField', [], {'max_length': '80', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        },
        'ets.removedltis': {
            'Meta': {'object_name': 'RemovedLtis', 'db_table': "u'waybill_removed_ltis'"},
            'lti': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['ets.LtiOriginal']", 'primary_key': 'True'})
        },
        'ets.sitracker': {
            'LTI': ('django.db.models.fields.related.OneToOneField', [], {'related_name': "'sitracker'", 'unique': 'True', 'primary_key': 'True', 'to': "orm['ets.LtiOriginal']"}),
            'Meta': {'object_name': 'SiTracker'},
            'number_units_left': ('django.db.models.fields.DecimalField', [], {'max_digits': '10', 'decimal_places': '3'}),
            'number_units_start': ('django.db.models.fields.DecimalField', [], {'max_digits': '10', 'decimal_places': '3'})
        },
        'ets.userprofile': {
            'Meta': {'object_name': 'UserProfile'},
            'compasUser': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'profiles'", 'null': 'True', 'to': "orm['ets.EpicPerson']"}),
            'isAllReceiver': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'isCompasUser': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'isDispatcher': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'isReciever': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'readerUser': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'receptionPoints': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['ets.ReceptionPoint']", 'null': 'True', 'blank': 'True'}),
            'superUser': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['auth.User']", 'unique': 'True', 'primary_key': 'True'}),
            'warehouses': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['ets.DispatchPoint']", 'null': 'True', 'blank': 'True'})
        },
        'ets.userprofileauditlogentry': {
            'Meta': {'ordering': "('-action_date',)", 'object_name': 'UserProfileAuditLogEntry'},
            'action_date': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'action_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'action_type': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            'action_user': ('audit_log.models.fields.LastUserField', [], {'related_name': "'_userprofile_audit_log_entry'", 'null': 'True', 'to': "orm['auth.User']"}),
            'compasUser': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'_auditlog_profiles'", 'null': 'True', 'to': "orm['ets.EpicPerson']"}),
            'isAllReceiver': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'isCompasUser': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'isDispatcher': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'isReciever': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'readerUser': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'receptionPoints': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['ets.ReceptionPoint']", 'null': 'True', 'blank': 'True'}),
            'superUser': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['auth.User']"}),
            'warehouses': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['ets.DispatchPoint']", 'null': 'True', 'blank': 'True'})
        },
        'ets.waybill': {
            'Meta': {'object_name': 'Waybill'},
            'auditComment': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'containerOneNumber': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'containerOneRemarksDispatch': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'containerOneRemarksReciept': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'containerOneSealNumber': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'containerTwoNumber': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'containerTwoRemarksDispatch': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'containerTwoRemarksReciept': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'containerTwoSealNumber': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'created': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'dateOfDispatch': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'dateOfLoading': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'destinationWarehouse': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'recipient_waybills'", 'to': "orm['ets.Place']"}),
            'dispatchRemarks': ('django.db.models.fields.CharField', [], {'max_length': '200', 'blank': 'True'}),
            'dispatch_warehouse': ('django.db.models.fields.related.ForeignKey', [], {'default': "u'ISBX002'", 'related_name': "'dispatch_waybills'", 'to': "orm['ets.Place']"}),
            'dispatcherName': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'dispatcherSigned': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'dispatcherTitle': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'invalidated': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'ltiNumber': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'recipientArrivalDate': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'recipientConsingee': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'recipientDistance': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'recipientEndDischargeDate': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'recipientLocation': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'recipientName': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'recipientRemarks': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'recipientSigned': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'recipientSignedTimestamp': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'recipientStartDischargeDate': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'recipientTitle': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'slug': ('autoslug.fields.AutoSlugField', [], {'unique_with': '()', 'max_length': '50', 'primary_key': 'True', 'unique': 'True', 'populate_from': 'None', 'db_index': 'True'}),
            'status': ('django.db.models.fields.IntegerField', [], {'default': '1'}),
            'transactionType': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'transportContractor': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'transportDeliverySigned': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'transportDeliverySignedTimestamp': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'transportDispachSigned': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'transportDispachSignedTimestamp': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'transportDriverLicenceID': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'transportDriverName': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'transportSubContractor': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'transportTrailerRegistration': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'transportType': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'transportVehicleRegistration': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'waybillNumber': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'waybillProcessedForPayment': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'waybillRecSentToCompas': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'waybillReceiptValidated': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'waybillSentToCompas': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'waybillValidated': ('django.db.models.fields.BooleanField', [], {'default': 'False'})
        },
        'ets.waybillauditlogentry': {
            'Meta': {'ordering': "('-action_date',)", 'object_name': 'WaybillAuditLogEntry'},
            'action_date': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'action_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'action_type': ('django.db.models.fields.CharField', [], {'max_length': '1'}),
            'action_user': ('audit_log.models.fields.LastUserField', [], {'related_name': "'_waybill_audit_log_entry'", 'null': 'True', 'to': "orm['auth.User']"}),
            'auditComment': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'containerOneNumber': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'containerOneRemarksDispatch': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'containerOneRemarksReciept': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'containerOneSealNumber': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'containerTwoNumber': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'containerTwoRemarksDispatch': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'containerTwoRemarksReciept': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'containerTwoSealNumber': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'created': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'dateOfDispatch': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'dateOfLoading': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'destinationWarehouse': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'_auditlog_recipient_waybills'", 'to': "orm['ets.Place']"}),
            'dispatchRemarks': ('django.db.models.fields.CharField', [], {'max_length': '200', 'blank': 'True'}),
            'dispatch_warehouse': ('django.db.models.fields.related.ForeignKey', [], {'default': "u'ISBX002'", 'related_name': "'_auditlog_dispatch_waybills'", 'to': "orm['ets.Place']"}),
            'dispatcherName': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'dispatcherSigned': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'dispatcherTitle': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'invalidated': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'ltiNumber': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'recipientArrivalDate': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'recipientConsingee': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'recipientDistance': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'recipientEndDischargeDate': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'recipientLocation': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'recipientName': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'recipientRemarks': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'recipientSigned': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'recipientSignedTimestamp': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'recipientStartDischargeDate': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'recipientTitle': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'slug': ('autoslug.fields.AutoSlugField', [], {'unique_with': '()', 'max_length': '50', 'populate_from': 'None', 'db_index': 'True'}),
            'status': ('django.db.models.fields.IntegerField', [], {'default': '1'}),
            'transactionType': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'transportContractor': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'transportDeliverySigned': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'transportDeliverySignedTimestamp': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'transportDispachSigned': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'transportDispachSignedTimestamp': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'transportDriverLicenceID': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'transportDriverName': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'transportSubContractor': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'transportTrailerRegistration': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'transportType': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'transportVehicleRegistration': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'waybillNumber': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'waybillProcessedForPayment': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'waybillRecSentToCompas': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'waybillReceiptValidated': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'waybillSentToCompas': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'waybillValidated': ('django.db.models.fields.BooleanField', [], {'default': 'False'})
        }
    }

    complete_apps = ['ets']
